// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_planner.proto

#include "local_planner.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace roborts_local_planner {
class LocalAlgorithmsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LocalAlgorithms>
      _instance;
} _LocalAlgorithms_default_instance_;
}  // namespace roborts_local_planner
namespace protobuf_local_5fplanner_2eproto {
static void InitDefaultsLocalAlgorithms() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::roborts_local_planner::_LocalAlgorithms_default_instance_;
    new (ptr) ::roborts_local_planner::LocalAlgorithms();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::roborts_local_planner::LocalAlgorithms::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LocalAlgorithms =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLocalAlgorithms}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_LocalAlgorithms.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_local_planner::LocalAlgorithms, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_local_planner::LocalAlgorithms, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_local_planner::LocalAlgorithms, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_local_planner::LocalAlgorithms, selected_algorithm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_local_planner::LocalAlgorithms, frequency_),
  ~0u,
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::roborts_local_planner::LocalAlgorithms)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::roborts_local_planner::_LocalAlgorithms_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "local_planner.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023local_planner.proto\022\025roborts_local_pla"
      "nner\"N\n\017LocalAlgorithms\022\014\n\004name\030\001 \003(\t\022\032\n"
      "\022selected_algorithm\030\002 \001(\t\022\021\n\tfrequency\030\003"
      " \001(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "local_planner.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_local_5fplanner_2eproto
namespace roborts_local_planner {

// ===================================================================

void LocalAlgorithms::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LocalAlgorithms::kNameFieldNumber;
const int LocalAlgorithms::kSelectedAlgorithmFieldNumber;
const int LocalAlgorithms::kFrequencyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LocalAlgorithms::LocalAlgorithms()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_local_5fplanner_2eproto::scc_info_LocalAlgorithms.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_local_planner.LocalAlgorithms)
}
LocalAlgorithms::LocalAlgorithms(const LocalAlgorithms& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      name_(from.name_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_selected_algorithm()) {
    selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
  }
  frequency_ = from.frequency_;
  // @@protoc_insertion_point(copy_constructor:roborts_local_planner.LocalAlgorithms)
}

void LocalAlgorithms::SharedCtor() {
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frequency_ = 0;
}

LocalAlgorithms::~LocalAlgorithms() {
  // @@protoc_insertion_point(destructor:roborts_local_planner.LocalAlgorithms)
  SharedDtor();
}

void LocalAlgorithms::SharedDtor() {
  selected_algorithm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LocalAlgorithms::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LocalAlgorithms::descriptor() {
  ::protobuf_local_5fplanner_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_local_5fplanner_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LocalAlgorithms& LocalAlgorithms::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_local_5fplanner_2eproto::scc_info_LocalAlgorithms.base);
  return *internal_default_instance();
}


void LocalAlgorithms::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    selected_algorithm_.ClearNonDefaultToEmptyNoArena();
  }
  frequency_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool LocalAlgorithms::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_local_planner.LocalAlgorithms)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            static_cast<int>(this->name(this->name_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_local_planner.LocalAlgorithms.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string selected_algorithm = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selected_algorithm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_local_planner.LocalAlgorithms.selected_algorithm");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double frequency = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_frequency();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &frequency_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_local_planner.LocalAlgorithms)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_local_planner.LocalAlgorithms)
  return false;
#undef DO_
}

void LocalAlgorithms::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional string selected_algorithm = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.selected_algorithm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->selected_algorithm(), output);
  }

  // optional double frequency = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->frequency(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_local_planner.LocalAlgorithms)
}

::google::protobuf::uint8* LocalAlgorithms::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roborts_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional string selected_algorithm = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.selected_algorithm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->selected_algorithm(), target);
  }

  // optional double frequency = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->frequency(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_local_planner.LocalAlgorithms)
  return target;
}

size_t LocalAlgorithms::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_local_planner.LocalAlgorithms)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string name = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->name_size());
  for (int i = 0, n = this->name_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string selected_algorithm = 2;
    if (has_selected_algorithm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selected_algorithm());
    }

    // optional double frequency = 3;
    if (has_frequency()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LocalAlgorithms::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_local_planner.LocalAlgorithms)
  GOOGLE_DCHECK_NE(&from, this);
  const LocalAlgorithms* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LocalAlgorithms>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_local_planner.LocalAlgorithms)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_local_planner.LocalAlgorithms)
    MergeFrom(*source);
  }
}

void LocalAlgorithms::MergeFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_local_planner.LocalAlgorithms)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  name_.MergeFrom(from.name_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_selected_algorithm();
      selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
    }
    if (cached_has_bits & 0x00000002u) {
      frequency_ = from.frequency_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void LocalAlgorithms::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocalAlgorithms::CopyFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalAlgorithms::IsInitialized() const {
  return true;
}

void LocalAlgorithms::Swap(LocalAlgorithms* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LocalAlgorithms::InternalSwap(LocalAlgorithms* other) {
  using std::swap;
  name_.InternalSwap(CastToBase(&other->name_));
  selected_algorithm_.Swap(&other->selected_algorithm_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(frequency_, other->frequency_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LocalAlgorithms::GetMetadata() const {
  protobuf_local_5fplanner_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_local_5fplanner_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace roborts_local_planner
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::roborts_local_planner::LocalAlgorithms* Arena::CreateMaybeMessage< ::roborts_local_planner::LocalAlgorithms >(Arena* arena) {
  return Arena::CreateInternal< ::roborts_local_planner::LocalAlgorithms >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
