// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inflation_layer_setting.proto

#include "inflation_layer_setting.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace roborts_costmap {
class ParaInflationLayerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ParaInflationLayer>
      _instance;
} _ParaInflationLayer_default_instance_;
}  // namespace roborts_costmap
namespace protobuf_inflation_5flayer_5fsetting_2eproto {
static void InitDefaultsParaInflationLayer() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::roborts_costmap::_ParaInflationLayer_default_instance_;
    new (ptr) ::roborts_costmap::ParaInflationLayer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::roborts_costmap::ParaInflationLayer::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ParaInflationLayer =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsParaInflationLayer}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ParaInflationLayer.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, inflation_radius_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, cost_scaling_factor_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, is_debug_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::roborts_costmap::ParaInflationLayer, is_raw_rosmessage_),
  0,
  1,
  2,
  3,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::roborts_costmap::ParaInflationLayer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::roborts_costmap::_ParaInflationLayer_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "inflation_layer_setting.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035inflation_layer_setting.proto\022\017roborts"
      "_costmap\"x\n\022ParaInflationLayer\022\030\n\020inflat"
      "ion_radius\030\001 \002(\001\022\033\n\023cost_scaling_factor\030"
      "\002 \002(\001\022\020\n\010is_debug\030\003 \002(\010\022\031\n\021is_raw_rosmes"
      "sage\030\004 \002(\010"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 170);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "inflation_layer_setting.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_inflation_5flayer_5fsetting_2eproto
namespace roborts_costmap {

// ===================================================================

void ParaInflationLayer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParaInflationLayer::kInflationRadiusFieldNumber;
const int ParaInflationLayer::kCostScalingFactorFieldNumber;
const int ParaInflationLayer::kIsDebugFieldNumber;
const int ParaInflationLayer::kIsRawRosmessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParaInflationLayer::ParaInflationLayer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_inflation_5flayer_5fsetting_2eproto::scc_info_ParaInflationLayer.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_costmap.ParaInflationLayer)
}
ParaInflationLayer::ParaInflationLayer(const ParaInflationLayer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&inflation_radius_, &from.inflation_radius_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_raw_rosmessage_) -
    reinterpret_cast<char*>(&inflation_radius_)) + sizeof(is_raw_rosmessage_));
  // @@protoc_insertion_point(copy_constructor:roborts_costmap.ParaInflationLayer)
}

void ParaInflationLayer::SharedCtor() {
  ::memset(&inflation_radius_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_raw_rosmessage_) -
      reinterpret_cast<char*>(&inflation_radius_)) + sizeof(is_raw_rosmessage_));
}

ParaInflationLayer::~ParaInflationLayer() {
  // @@protoc_insertion_point(destructor:roborts_costmap.ParaInflationLayer)
  SharedDtor();
}

void ParaInflationLayer::SharedDtor() {
}

void ParaInflationLayer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ParaInflationLayer::descriptor() {
  ::protobuf_inflation_5flayer_5fsetting_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inflation_5flayer_5fsetting_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParaInflationLayer& ParaInflationLayer::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_inflation_5flayer_5fsetting_2eproto::scc_info_ParaInflationLayer.base);
  return *internal_default_instance();
}


void ParaInflationLayer::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_costmap.ParaInflationLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 15u) {
    ::memset(&inflation_radius_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&is_raw_rosmessage_) -
        reinterpret_cast<char*>(&inflation_radius_)) + sizeof(is_raw_rosmessage_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParaInflationLayer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_costmap.ParaInflationLayer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double inflation_radius = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_inflation_radius();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &inflation_radius_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double cost_scaling_factor = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_cost_scaling_factor();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &cost_scaling_factor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool is_debug = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_is_debug();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_debug_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool is_raw_rosmessage = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_is_raw_rosmessage();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_raw_rosmessage_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_costmap.ParaInflationLayer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_costmap.ParaInflationLayer)
  return false;
#undef DO_
}

void ParaInflationLayer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_costmap.ParaInflationLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double inflation_radius = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->inflation_radius(), output);
  }

  // required double cost_scaling_factor = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->cost_scaling_factor(), output);
  }

  // required bool is_debug = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->is_debug(), output);
  }

  // required bool is_raw_rosmessage = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->is_raw_rosmessage(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_costmap.ParaInflationLayer)
}

::google::protobuf::uint8* ParaInflationLayer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roborts_costmap.ParaInflationLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double inflation_radius = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->inflation_radius(), target);
  }

  // required double cost_scaling_factor = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->cost_scaling_factor(), target);
  }

  // required bool is_debug = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->is_debug(), target);
  }

  // required bool is_raw_rosmessage = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->is_raw_rosmessage(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_costmap.ParaInflationLayer)
  return target;
}

size_t ParaInflationLayer::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:roborts_costmap.ParaInflationLayer)
  size_t total_size = 0;

  if (has_inflation_radius()) {
    // required double inflation_radius = 1;
    total_size += 1 + 8;
  }

  if (has_cost_scaling_factor()) {
    // required double cost_scaling_factor = 2;
    total_size += 1 + 8;
  }

  if (has_is_debug()) {
    // required bool is_debug = 3;
    total_size += 1 + 1;
  }

  if (has_is_raw_rosmessage()) {
    // required bool is_raw_rosmessage = 4;
    total_size += 1 + 1;
  }

  return total_size;
}
size_t ParaInflationLayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_costmap.ParaInflationLayer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required double inflation_radius = 1;
    total_size += 1 + 8;

    // required double cost_scaling_factor = 2;
    total_size += 1 + 8;

    // required bool is_debug = 3;
    total_size += 1 + 1;

    // required bool is_raw_rosmessage = 4;
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParaInflationLayer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_costmap.ParaInflationLayer)
  GOOGLE_DCHECK_NE(&from, this);
  const ParaInflationLayer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParaInflationLayer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_costmap.ParaInflationLayer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_costmap.ParaInflationLayer)
    MergeFrom(*source);
  }
}

void ParaInflationLayer::MergeFrom(const ParaInflationLayer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_costmap.ParaInflationLayer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      inflation_radius_ = from.inflation_radius_;
    }
    if (cached_has_bits & 0x00000002u) {
      cost_scaling_factor_ = from.cost_scaling_factor_;
    }
    if (cached_has_bits & 0x00000004u) {
      is_debug_ = from.is_debug_;
    }
    if (cached_has_bits & 0x00000008u) {
      is_raw_rosmessage_ = from.is_raw_rosmessage_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParaInflationLayer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_costmap.ParaInflationLayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParaInflationLayer::CopyFrom(const ParaInflationLayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_costmap.ParaInflationLayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParaInflationLayer::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  return true;
}

void ParaInflationLayer::Swap(ParaInflationLayer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParaInflationLayer::InternalSwap(ParaInflationLayer* other) {
  using std::swap;
  swap(inflation_radius_, other->inflation_radius_);
  swap(cost_scaling_factor_, other->cost_scaling_factor_);
  swap(is_debug_, other->is_debug_);
  swap(is_raw_rosmessage_, other->is_raw_rosmessage_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ParaInflationLayer::GetMetadata() const {
  protobuf_inflation_5flayer_5fsetting_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inflation_5flayer_5fsetting_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace roborts_costmap
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::roborts_costmap::ParaInflationLayer* Arena::CreateMaybeMessage< ::roborts_costmap::ParaInflationLayer >(Arena* arena) {
  return Arena::CreateInternal< ::roborts_costmap::ParaInflationLayer >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
